// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCA5qdkvN13Xje5-V9SsPpC-k3nQ8D5Zaw',
    appId: '1:461427127162:web:3026e581a3597a08765cc3',
    messagingSenderId: '461427127162',
    projectId: 'dev-bjjmatch',
    authDomain: 'dev-bjjmatch.firebaseapp.com',
    storageBucket: 'dev-bjjmatch.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQJ97pO6jOts0KpLClMVlG_fYa0wXRqh4',
    appId: '1:461427127162:android:f2dbb8cbcfccf223765cc3',
    messagingSenderId: '461427127162',
    projectId: 'dev-bjjmatch',
    storageBucket: 'dev-bjjmatch.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANHBKTWrLZDAEyexo7uj0DBgiICLQ0W3k',
    appId: '1:461427127162:ios:dbd9d60b93179975765cc3',
    messagingSenderId: '461427127162',
    projectId: 'dev-bjjmatch',
    storageBucket: 'dev-bjjmatch.firebasestorage.app',
    iosBundleId: 'com.example.bjjapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANHBKTWrLZDAEyexo7uj0DBgiICLQ0W3k',
    appId: '1:461427127162:ios:dbd9d60b93179975765cc3',
    messagingSenderId: '461427127162',
    projectId: 'dev-bjjmatch',
    storageBucket: 'dev-bjjmatch.firebasestorage.app',
    iosBundleId: 'com.example.bjjapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCA5qdkvN13Xje5-V9SsPpC-k3nQ8D5Zaw',
    appId: '1:461427127162:web:20663373c71d3b06765cc3',
    messagingSenderId: '461427127162',
    projectId: 'dev-bjjmatch',
    authDomain: 'dev-bjjmatch.firebaseapp.com',
    storageBucket: 'dev-bjjmatch.firebasestorage.app',
  );
}
