// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqznBYo-dUL_dR_ELf4QYb5Mh_qXFlNyo',
    appId: '1:985483936480:android:87b9a79ff8b9e584da4685',
    messagingSenderId: '985483936480',
    projectId: 'matchbjj--dev',
    storageBucket: 'matchbjj--dev.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkZILPrOTNJhxk1lmv2IFPT63g3zr3yhw',
    appId: '1:985483936480:web:4c944290a4e29d3cda4685',
    messagingSenderId: '985483936480',
    projectId: 'matchbjj--dev',
    authDomain: 'matchbjj--dev.firebaseapp.com',
    storageBucket: 'matchbjj--dev.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDY3B3MC49-2MksniQfghFo4ShHEovn4do',
    appId: '1:985483936480:ios:d49c5ec9ae46ce48da4685',
    messagingSenderId: '985483936480',
    projectId: 'matchbjj--dev',
    storageBucket: 'matchbjj--dev.firebasestorage.app',
    iosBundleId: 'com.example.bjjapp',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDY3B3MC49-2MksniQfghFo4ShHEovn4do',
    appId: '1:985483936480:ios:d49c5ec9ae46ce48da4685',
    messagingSenderId: '985483936480',
    projectId: 'matchbjj--dev',
    storageBucket: 'matchbjj--dev.firebasestorage.app',
    iosBundleId: 'com.example.bjjapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkZILPrOTNJhxk1lmv2IFPT63g3zr3yhw',
    appId: '1:985483936480:web:4e41b3004cc620afda4685',
    messagingSenderId: '985483936480',
    projectId: 'matchbjj--dev',
    authDomain: 'matchbjj--dev.firebaseapp.com',
    storageBucket: 'matchbjj--dev.firebasestorage.app',
  );

}