// lib/firebase_options_prod.dart

// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart'
    show FirebaseOptions; // <-- CORRIGIDO AQUI
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      // CONFIGURAÇÃO WEB ADICIONADA AQUI
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // CÓDIGO WEB COM SUAS CHAVES
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxtyejLeFMErqGtHU-NCvhVFG6US6OylU',
    appId: '1:757933813601:web:2f7aabfec9765eb18c9f20',
    messagingSenderId: '757933813601',
    projectId: 'matchbjj',
    authDomain: 'matchbjj.firebaseapp.com',
    storageBucket: 'matchbjj.firebasestorage.app',
    measurementId: 'G-VBQLGV95WN',
  );

  // CÓDIGO ANDROID (JÁ EXISTENTE)
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVhpVDU3o5QT4v9XXXaUzbCyWm0R_Yo8s',
    appId: '1:757933813601:android:af1462c0e58058fb8c9f20',
    messagingSenderId: '757933813601',
    projectId: 'matchbjj',
    storageBucket: 'matchbjj.firebasestorage.app',
  );
}
